minimumReleaseAgeExclude:
  - "@chat-adapter/*"
  - "@ai-sdk/*"
  - "@vercel/*"
  - "@workflow/*"
  - eve
  - ai
  - chat
  - workflow

ignoredOptionalDependencies:
  - "@mongodb-js/zstd"
  - "node-liblzma"

allowBuilds:
  esbuild@0.27.0: true
